### ISSUE TITLE
部分漫画无法转换

### ISSUE THREAD

**Issue by noirfy** [xyoye/ComicTools#1]
我在手机里缓存了《钢之炼金术师》，但是 app 显示没有转换的页数。但是转换其他漫画没问题。
我猜是 B 漫把网易漫画的资源直接拿过来用了（钢炼原本是网易版权的），网易的图片转换方式和 B 慢的不同。
大佬有空研究下是否原因吧

**Comment by xyoye** [comment]
已更新，支持钢炼转换
钢炼是png.view，之前只支持jpg.view转换

**Comment by noirfy** [comment]
Ok 了，谢谢 ^_^
